services:
  notifyhub:
    image: notifyhub
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - "./data:/app/data"
    environment:
      - DATABASE_URL=sqlite:////app/data/notifyhub.db
    restart: unless-stopped
